services:
  rustdo:
    build: .
    image: ubermetroid/rustdo:latest
    container_name: rustdo
    restart: unless-stopped
    ports:
      - ${DUMBDO_PORT:-3000}:3000
    volumes:
      - ${DUMBDO_DATA_PATH:-./data}:/app/data
    environment:
      - DUMBDO_PIN=${DUMBDO_PIN-}
      - DUMBDO_SITE_TITLE=RustDo
      - SINGLE_LIST=${SINGLE_LIST:-false}
