services:
  rustdo:
    build: .
    image: ubermetroid/rustdo:latest
    container_name: rustdo
    restart: unless-stopped
    ports:
      - ${RUSTDO_PORT:-4403}:4403
    volumes:
      - ${RUSTDO_DATA_PATH:-./data}:/app/data
    environment:
      - PORT=4403
      - RUSTDO_PIN=${RUSTDO_PIN-}
      - RUSTDO_SITE_TITLE=RustDo
      - SINGLE_LIST=${SINGLE_LIST:-false}
